
target 'IQKeyboardManagerSwiftdemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fynd
pod 'MXSegmentedPager'
pod 'Alamofire'
pod 'expanding-collection'
pod 'GoogleMaps'
pod 'DLRadioButton', '~> 1.4'
pod 'FSCalendar'
pod 'SDWebImage'
pod 'IQKeyboardManagerSwift'
pod 'MBProgressHUD'
end

